### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SergeiSemenkov** [pentaho/mondrian#1228]
I can't build mondrian anymore.
Now I get this error:

Downloading from pentaho-public: https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/org/codehaus/mojo/build-helper-maven-plugin/3.1.0-pentaho/build-helper-maven-plugin-3.1.0-pentaho.pom
[ERROR] Plugin org.codehaus.mojo:build-helper-maven-plugin:3.1.0-pentaho or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:build-helper-maven-plugin:jar:3.1.0-pentaho: Could not transfer artifact org.codehaus.mojo:build-helper-maven-plugin:pom:3.1.0-pentaho from/to pentaho-public (https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn): repo.orl.eng.hitachivantara.com: 
Unknown host repo.orl.eng.hitachivantara.com

How to fix this?

**Comment by EdToro74** [comment]
Were you able to figure this out?  I get the same error.

**Comment by SergeiSemenkov** [comment]
Hi. I got help from Hitachy guy. Thanks him a lot.
You need to add mirror to maven config.xml.

```
<mirror>
   <id>pentaho-nexus</id>
   <url>http://nexus.pentaho.org/content/groups/omni</url>
   <mirrorOf>*</mirrorOf>
</mirror>

```
