### ISSUE TITLE
Make mondrian working with Spark sql JDBC

### ISSUE THREAD

**Issue by standino** [pentaho/mondrian#369]
Thanks team to create such wonderful tool. I am very like it. 

I would like to know if there is a plan to support spark-sql-jdbc. Below is a topic about it.

http://stackoverflow.com/questions/24631833/spark-sql-jdbc-support

Please help to make mondrian working with it and give us some instruction for that. 

Thanks very much.

**Comment by vinceyang** [comment]
+1
