### ISSUE TITLE
Last Known Price - Mondrian Error: Query required more than 12 iterations

### ISSUE THREAD

**Issue by sanjayraja** [pentaho/mondrian#437]
Hi,

I have written an MDX Query to retrieve the last known price.

```
With 
MEMBER [Measures].[Last Known Price]
AS IIF(isEmpty([Measures].[Ex Showroom Price]),([Transaction Date].[Month].PrevMember,[Measures].[Last Known Price]),[Measures].[Ex Showroom Price])
Select { [Measures].[Last Known Price] } on Columns, {{[Transaction Date].[Month].[September 2014],[Transaction Date].[Month].[October 2014],[Transaction Date].[Month].[November 2014],[Transaction Date].[Month].[December 2014],[Transaction Date].[Month].[January 2015],[Transaction Date].[Month].[February 2015],[Transaction Date].[Month].[March 2015]}
*
{[Brand].[Brand].Children}} on Rows 
From [pricingCube] Where { {[Body Type].[Body Type].[SUV]} }
```

On execution it given me an error 

```
The Mondrian XML: Mondrian Error:Internal error: Query required more than 12 iterations
```

I have tried increasing the mondrian.rolap.evaluate.MaxEvalDepth to no avail.

It works fine and fast when the number of Dimensional Items in the Dimension is less than say 15/20.
In the above Query if I replace Brand with Manufacturer - it work just fine

```
With 
MEMBER [Measures].[Last Known Price]
AS IIF(isEmpty([Measures].[Ex Showroom Price]),([Transaction Date].[Month].PrevMember,[Measures].[Last Known Price]),[Measures].[Ex Showroom Price])
Select { [Measures].[Last Known Price] } on Columns, {{[Transaction Date].[Month].[September 2014],[Transaction Date].[Month].[October 2014],[Transaction Date].[Month].[November 2014],[Transaction Date].[Month].[December 2014],[Transaction Date].[Month].[January 2015],[Transaction Date].[Month].[February 2015],[Transaction Date].[Month].[March 2015]}
*
{[Manufacturer].[Manufacturer].Children}} on Rows 
From [pricingCube] Where { {[Body Type].[Body Type].[SUV]} }
```

I am using Mondrian 3.7.

Can someone please help/guide me ?

Regards,
Sanjay

**Comment by berkinthomas** [comment]
The problem is, you are using the same alias "[Measures].[Last Known Price] " in the calculated member. So the loop begins here. Please try with different alias , it will definitely works..

**Comment by sanjayraja** [comment]
Thanks Thomas,
But I was looking at this as a recursive function. 

My objective is to get the last known price of an entity, without having to repeat (load) the price of if has not changed.

If you have a work around please do suggest 

Warm Regards,
Sanjay Raja

**Comment by berkinthomas** [comment]
I think, you don't need recursive method to solve this problem. Just use two metrics as  I said. Please check with your query and let me know the result with your query

**Comment by sanjayraja** [comment]
Thanks berkins - It seems to be working. I will do some more tests and revert.

**Comment by sanjayraja** [comment]
Thanks Thomas - It seems to be working, will try out a few more scenarios.

**Comment by sanjayraja** [comment]
Hi Thomas,

I tried and it works only when the immediate previous Month has a value, 
````
([Transaction Date].[Month].PrevMember] will check for the previous Month) 
````
and if that does not have a value then it does not check for older months. So it returns Empty.
This was the reason where the CalculatedMember was itself used in the With Member.

Trying to achieve Last Ever Non Empty -  something similar to  
https://cwebbbi.wordpress.com/2011/03/24/last-ever-non-empty-a-new-fast-mdx-approach/

**Comment by sanjayraja** [comment]
Basically , I will need to do 
[Transaction Date].[Month].PrevMember.PrevMember.PrevMember...n times] to get the Last Known Price
