### ISSUE TITLE
Datediff function produce wrong result for different month

### ISSUE THREAD

**Issue by berkinthomas** [pentaho/mondrian#444]
/*** Query ***/

With Member Measures.DD as DateDiff('d',CDate('Mar 20, 2014'),CDate('Apr 19, 2014'))
select {Measures.DD} on Columns 
 from [Cube_AR]

/*** Result ***/
1

/*** Expected Result ***/
30

**Comment by mkambol** [comment]
You've selected the interval 'd' in your query, which corresponds to the day of month, resulting in 20-19=1.  What you want is 'y' (day of year).  Here's the list of supported intervals:

        yyyy("Year", Calendar.YEAR),
        q("Quarter", -1),
        m("Month", Calendar.MONTH),
        y("Day of year", Calendar.DAY_OF_YEAR),
        d("Day", Calendar.DAY_OF_MONTH),
        w("Weekday", Calendar.DAY_OF_WEEK),
        ww("Week", Calendar.WEEK_OF_YEAR),
        h("Hour", Calendar.HOUR_OF_DAY),
        n("Minute", Calendar.MINUTE),
        s("Second", Calendar.SECOND);

**Comment by berkinthomas** [comment]
No, Please check with 'y' for different year. Which will produce wrong result. 30

With Member Measures.DD as DateDiff('y',CDate('Mar 20, 2014'),CDate('Apr 19, 2014'))
select {Measures.DD} on Columns 
from [Cube_AR]

**Comment by mkambol** [comment]
Can we continue this just on the forum?  I'd rather not split the conversation in two places.

**Comment by berkinthomas** [comment]
Ok. please let me know the forum details..

Please make sure that this issue was not closed.

**Comment by mkambol** [comment]
The forum thread you started:  http://forums.pentaho.com/showthread.php?183989-Datediff-Error&p=403916#post403916

I don't have ready access to VBA scripting, so if you're able to show functional differences between Mondrian's datediff and vba's datediff that'd be worth mentioning.
