### ISSUE TITLE
SegmentCacheIndexRegistry don't use UseContentChecksum flag

### ISSUE THREAD

**Issue by KrzychuJedi** [pentaho/mondrian#835]
If I have two Rolap Connection with same schema content (so content checksum is equal) but with different data source (so schema key is different if I use JdbcConnectionUuid flag) SegmentCacheIndexRegistry use same registry for those two connections because it use star.getSchema().getChecksum() method as key.  This behavior couse that mondrian don't see diference beetwen this two connections and cache return same entryfor two different data sources.

**Comment by mbatchelor** [comment]
We don't follow git Issues - we use JIRA. This issue is reported in JIRA here: http://jira.pentaho.com/browse/MONDRIAN-2567

**Comment by lucboudreau** [comment]
This was fixed recently in favor of SchemaKey. Look for it in the next release.
