### ISSUE TITLE
Pentaho maven repository is down

### ISSUE THREAD

**Issue by LoicTosser** [pentaho/mondrian#853]
This morning the pentaho maven repository seems to be down.
Each download request during maven build fails with 503 error:

`[WARNING] Could not transfer metadata XXX/maven-metadata.xml from/to pentaho-releases (http://repository.pentaho.org/artifactory/repo/): Failed to transfer file: http://repository.pentaho.org/artifactory/repo/XXX/maven-metadata.xml. Return code is: 503 , ReasonPhrase:Service Temporarily Unavailable.`

**Comment by maxcapraro** [comment]
While it has been working for me after March 14th, it is down again. 

Is this repository deprecated and we should switch to another one? If yes: Which?

**Comment by BeckhamVinoth** [comment]
Yeah me too waiting for that solution . My builds are getting failed because of these pentaho: mondrian repository down .

**Comment by pamval** [comment]
Public facing artifactory was being migrated to a more recent version. 
Things should be back to stable now (since yesterday). 
Can you guys try again, please?

**Comment by BeckhamVinoth** [comment]
![screenshot 72](https://user-images.githubusercontent.com/19778883/29111331-7d8a78f8-7d07-11e7-8cc1-7f7bded6704a.png)
No , still am facing that issue . !!

**Comment by pamval** [comment]
Can you paste the build logs please? 

Also, if you're using maven, is your ~/.m2/settings.xml configured as stated here: https://github.com/pentaho/maven-parent-poms/blob/master/maven-support-files/settings.xml
?

**Comment by BeckhamVinoth** [comment]
Hey Buddy , Am using gradle

**Comment by maxcapraro** [comment]
Thanks @pamval! I realized from your link that I was using a wrong (probably by now disabled) repository URL in my settings.xml. 

@BeckhamVinoth: From your log output in the issue description, I assume you use the old URL too. It should be `http://nexus.pentaho.org/content/groups/omni`

Out of curiosity: Is there a particular reason for not using Maven central?

**Comment by BeckhamVinoth** [comment]
Thanks @maxcapraro  , you are correct . i was using the old url . now my issue solved . Thanks man :)

**Comment by pamval** [comment]
Just checked with the Eng. Ops team and the link for the Pentaho repo needs to be changed to nexus.pentaho.org/content/groups/omni

**Comment by mikelurquia** [comment]
Hi, I have changed the repo to the one you mention but I am still getting problems with dependencies:

```
<repository>
  <id>pentaho.resolve.repo</id>
  <name>Pentaho Omni</name>
  <url>http://nexus.pentaho.org/content/groups/omni</url>
</repository>
```

`<dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-core</artifactId>
            <version>7.1.0.0-57</version>
        </dependency>`

Am I missing any other change here?

**Comment by smfukaya** [comment]
I'm also having the same 503 error.

**Comment by YangDongSESA624380** [comment]
https://community.hitachivantara.com/discussion/publicnexuspentahoorg-unavailable

**Comment by YangDongSESA624380** [comment]
https://blog.csdn.net/weixin_40583191/article/details/103408125
